backend:
  name: github
  repo: suvarnajewellers/suvarnajewellers.github.io
  branch: main

media_folder: ""
public_folder: "/"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "products.json"
        label: "Products"
        name: "products"
        format: "json"
        fields:
          - {label: "Products", name: "products", widget: "list"}
